var Koa = require('koa')
var serve = require('koa-static')
var path = require('path')
var viewhook = require('./middlewares/viewhook')
var matchRoute = require('./middlewares/matchRoute')
var router = require('./controllers')
var routes = require('../common/redux/routes')

new Koa()
  .use(viewhook())
  .use(matchRoute(routes))
  .use(router.routes())
  .use(router.allowedMethods())
  .use(serve(path.join(process.cwd(), 'static')))
  .listen(3003)

console.log('listening on port 3003 --', process.env.NODE_ENV)
